### ISSUE TITLE
email dosen't output

### ISSUE THREAD

**Issue by med004** [contextio/PHP-Lite-ContextIO#18]
I use contextio for display all email but i haven't display any emails .. I install context php lite and integre webhooks and dosen't receive any email ..

code function : 

`
    public function contextAction()
    {
    	$apiKey = 'bdv39wr1';
		$apiSecret = 'QtA4WG9mzCpNlvkP';
		$accountId = '5a7364c56d5d992d945d54c3';
		// instantiate the contextio object
		$contextio = new ContextIO('kykfcie9', 'DHehj84DUoesLJMZ');
		$r = $contextio->listUsers();
//print_r($r->getData());

		$r = $contextio->addConnectToken(array(
  "callback_url" => "https://api.context.io/lite/users/5a7364c56d5d992d945d54c3")); 
			//print_r($r->getData()['token']);

		$args = array('folder' => 'Inbox','label' => 'all');
		$r = $contextio->listMessages('5a7364c56d5d992d945d54c3', $args);
		if ($r !== false) {
		    foreach ($r->getData() as $message) {
		        echo "Subject: ".$message['subject']."<br>";
		    }
		} else {
		    print_r($contextio->getLastResponse());
		}

		//print_r($contextio->getLastResponse());
		
		return new Response("test");

	
    }`

in logs in site contextio I have this output:

https://imgur.com/a/8MXSr

and in my localserver i have this output:

https://imgur.com/a/ePccC

what is errors please and what is label in parameters function

**Comment by sushithegreat** [comment]
Your callback url should be a url that you host. Check out the docs [here](https://docs.context.io/#receiving-webhook-callbacks) and email support@context.io for questions specific to the API.
